### ISSUE TITLE
convert mbn to bin format

### ISSUE THREAD

**Issue by coolirc** [andersson/pil-squasher#1]
Hello can you provide a script that does the conversion from mbn format to bin format ?
thanks for help

**Comment by andersson** [comment]
Which "bin" format are you referring to?

**Comment by coolirc** [comment]
Hello Andersson , it's glad to see that you replied to my 2019 question in 2020 :) but anyway .
i was talking about .bin files similar to ZTE devices firmwares  like in this repo https://github.com/forth32/qtools/tree/master/loaders
you see all patched loaders are in bin format  but in original firmware package we find the same loader unpatched in .mbn format . so in order to patch the loader i think it must be in .bin format but as i had replies from other forum it's already in the bin format .

**Comment by z3ntu** [comment]
I guess this can be closed then?

**Comment by JamiKettunen** [comment]
@coolirc Mind closing this issue? I've indeed also seen manually squashed `.mbn` files also duplicated as `.elf` (not quite `.bin` but close enough I think) files (`sha256sum`s match on both) on my OnePlus 5 firmware partitions, example being `a540_zap.elf` vs `a540_zap.{mdt,b*}` on the `vendor` (`/dev/sdf6`) partition.

**Comment by coolirc** [comment]
Solved ! thanks
