### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by JamiKettunen** [andersson/pil-squasher#6]
As per https://github.com/andersson/pil-squasher/blob/e8573fe/pil-squasher.c#L1-L30 the source code is licensed under a [BSD-3-Clause](https://spdx.org/licenses/BSD-3-Clause.html), yet the repository root is missing a `LICENSE` file, which is required to be distributed along with installed binaries.

**Comment by lumag** [comment]
@andersson could you please add the `LICENSE` file?
