### ISSUE TITLE
Hello help wanted 

### ISSUE THREAD

**Issue by Saikatsaha1996** [andersson/pil-squasher#7]
I just want to guide.. i want to build my device firmware to mbn file how to build..

![IMG_20230519_201908_325](https://github.com/andersson/pil-squasher/assets/72664192/aa72802b-5dd6-4bfc-88e0-db1fc891257f)

**Comment by Saikatsaha1996** [comment]
Anyone can help? How to compile elf format Firmware? Bdwlan firmwares available but not available and mdt format

**Comment by konradybcio** [comment]
XX in bdwlan.eXX refers to the fused in board id, you should only use one of these files. Check this commit message for reference:

```
arm64: dts: qcom: sm6115p-j606f: Enable ATH10K WiFi
    
    Enable the onboard QCA Wi-Fi. HW identifiers for reference:
    qmi chip_id 0x320 chip_family 0x4001 board_id 0xff soc_id 0x400e0000
    
    Firmware sources:
    /vendor/firmware_mnt/image/wlanmdsp.bin -> qcom/.../wlanmdsp.mbn
    /vendor/firmware_mnt/image/bdwlan.bXX [1] -> [2] -> ath10k/.../board-2.bin
    [3] -> ath10k/.../firmware-5.bin
    
    Not sure where 3 comes from on the device itself, gotta investigate that..
    
    According to [4], it's called WCN3990_STRAIT.
    
    [1] XX = board_id printed when the file is missing or by your downstream
    kernel firmware loader in the dmesg; if XX=ff, use bdwlan.bin
    
    [2] https://github.com/jhugo/linux/blob/5.5rc2_wifi/README
    [3] https://github.com/kvalo/ath10k-firmware/blob/master/WCN3990/hw1.0/HL3.1/WLAN.HL.3.1-01040-QCAHLSWMTPLZ-1/firmware-5.bin
    [4] https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn/-/blob/LA.VENDOR.1.0.r1-20700-WAIPIO.QSSI13.0/hif/src/hif_hw_version.h#L55
```

**Comment by Saikatsaha1996** [comment]
> 

Thank you.. noted.. !
I will definitely ask you for help.. in mainline.. but still I am not sure.. I only have `bdwlan.xyz` files but unable to find out `wlanmdsp.xyz` ... In my device showing this file as a symbolic link to this location `/vendor/firmware_mnt/image/wlanmdsp.bin` but not available this file when I search..

I took my all this firmware.. which available in my device..
https://github.com/Saikatsaha1996/firmware-realme-porsche/tree/porsche/lib/firmware/qcom/sm8350/porsche

**Comment by Saikatsaha1996** [comment]
> XX in bdwlan.eXX refers to the fused in board id, you should only use one of these files. Check this commit message for reference:
> 
> ```
> arm64: dts: qcom: sm6115p-j606f: Enable ATH10K WiFi
>     
>     Enable the onboard QCA Wi-Fi. HW identifiers for reference:
>     qmi chip_id 0x320 chip_family 0x4001 board_id 0xff soc_id 0x400e0000
>     
>     Firmware sources:
>     /vendor/firmware_mnt/image/wlanmdsp.bin -> qcom/.../wlanmdsp.mbn
>     /vendor/firmware_mnt/image/bdwlan.bXX [1] -> [2] -> ath10k/.../board-2.bin
>     [3] -> ath10k/.../firmware-5.bin
>     
>     Not sure where 3 comes from on the device itself, gotta investigate that..
>     
>     According to [4], it's called WCN3990_STRAIT.
>     
>     [1] XX = board_id printed when the file is missing or by your downstream
>     kernel firmware loader in the dmesg; if XX=ff, use bdwlan.bin
>     
>     [2] https://github.com/jhugo/linux/blob/5.5rc2_wifi/README
>     [3] https://github.com/kvalo/ath10k-firmware/blob/master/WCN3990/hw1.0/HL3.1/WLAN.HL.3.1-01040-QCAHLSWMTPLZ-1/firmware-5.bin
>     [4] https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn/-/blob/LA.VENDOR.1.0.r1-20700-WAIPIO.QSSI13.0/hif/src/hif_hw_version.h#L55
> ```

I know it is no appropriate location for asked.. 
But I am asking here because you was shared some wlan related firmware data.. 

Now I am trying to up wifi.. but firmwares required.. for `ath11k` .. but I don't have any `wlanmdsp` firmware files..

I have bdwlan, amss, amss20, m3, and regdb... Now how can I create wifi firmware for my `ath11k` ? Just asked here because I don't know.. 

All firmwares in my first picture..
